# Generated by Django 4.0.4 on 2022-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techboxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemassigment',
            name='item',
            field=models.ManyToManyField(to='techboxapp.item'),
        ),
    ]
